# Generated by Django 5.0.6 on 2024-06-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={'ordering': ('id',)},
        ),
    ]
